### ISSUE TITLE
How i change the app bar color in chat window?

### ISSUE THREAD

**Issue by hs4426992-AR** [emostar/flutter-zendesk#7] opened 2019-09-05 11:04 UTC
I've already searched but no help is given.

**Comment by hs4426992-AR** [comment] 2019-09-05 11:05
please provide a solution

**Comment by xiaozihao92** [comment] 2019-12-03 07:19
https://developer.zendesk.com/embeddables/docs/android-chat-sdk/customization

**Comment by emostar** [comment] 2020-03-27 19:12
Duplicate of #10

**Closed by emostar** 2020-03-27 19:12 UTC
