### ISSUE TITLE
Update to SDK v2

### ISSUE THREAD

**Issue by VytorCalixto** [emostar/flutter-zendesk#17] opened 2020-04-14 14:40 UTC
The intercom [chat SDK v1](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/releasenotes) still uses the UIWebView API. The v2 was just released and fix this problem.

**Comment by emostar** [comment] 2020-04-15 00:52
Thanks for bringing this to my attention! I'll take a look at the docs and see what needs to be done to update to SDK v2.

It would be nice to get a notification from Zendesk when a big change like this comes out...

**Comment by KorbinianMossandl** [comment] 2020-04-17 13:06
@emostar 
there are pretty decen migration guides for both ios and Android:
https://developer.zendesk.com/embeddables/docs/chat-sdk-v-2-for-ios/migration
https://developer.zendesk.com/embeddables/docs/chat-sdk-v-2-for-android/migration

**Comment by alan2030** [comment] 2020-04-21 13:04
Yes, the same problem for me. Can't use Zendesk in my apps anymore :(

**Comment by colt005** [comment] 2020-04-23 10:38
Hello @emostar , Is this issue being resolved? It would be nice if we get an info on when this would get resolved, Thank you

**Comment by mjmon** [comment] 2020-05-03 04:49
Hello @emostar , I hope this is being addressed. :)

**Comment by bhargavsejpalindianic** [comment] 2020-05-04 14:29
Any update on this issue? how can I update to version that not using UIWebView

**Comment by emostar** [comment] 2020-05-05 00:20
I started the work for this in the branch, [zendesk-chat-v2](https://github.com/emostar/flutter-zendesk/tree/feature/zendesk-chat-v2)

Unfortunately, the example app crashes with the following output. I have run out of time to work on it for now, but will come back. If anyone is up to debugging the issue, check out the branch and give it a try.

```E/AndroidRuntime(24879): FATAL EXCEPTION: main                                                 
E/AndroidRuntime(24879): Process: com.codeheadlabs.zendeskexample, PID: 24879                  
E/AndroidRuntime(24879): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.codeheadlabs.zendeskexample/zendesk.messaging.MessagingActivity}: android.view.InflateException: Binary XML file line #2: Binary XML file line
 #2: Error inflating class zendesk.messaging.ui.MessagingView                                                                 
E/AndroidRuntime(24879):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2897)         
E/AndroidRuntime(24879):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2975)
E/AndroidRuntime(24879):        at android.app.ActivityThread.-wrap11(Unknown Source:0)  
E/AndroidRuntime(24879):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1705)
E/AndroidRuntime(24879):        at android.os.Handler.dispatchMessage(Handler.java:106)                       
E/AndroidRuntime(24879):        at android.os.Looper.loop(Looper.java:164)                                   
E/AndroidRuntime(24879):        at android.app.ActivityThread.main(ActivityThread.java:6615)                
E/AndroidRuntime(24879):        at java.lang.reflect.Method.invoke(Native Method)      
E/AndroidRuntime(24879):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime(24879):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
E/AndroidRuntime(24879): Caused by: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class zendesk.messaging.ui.MessagingView
E/AndroidRuntime(24879): Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class zendesk.messaging.ui.MessagingView
E/AndroidRuntime(24879): Caused by: java.lang.reflect.InvocationTargetException  
E/AndroidRuntime(24879):        at java.lang.reflect.Constructor.newInstance0(Native Method)                        
E/AndroidRuntime(24879):        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
E/AndroidRuntime(24879):        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
E/AndroidRuntime(24879):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
E/AndroidRuntime(24879):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
E/AndroidRuntime(24879):        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/AndroidRuntime(24879):        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
E/AndroidRuntime(24879):        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
E/AndroidRuntime(24879):        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
E/AndroidRuntime(24879):        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
E/AndroidRuntime(24879):        at zendesk.messaging.MessagingActivity.onCreate(MessagingActivity.java:126)
E/AndroidRuntime(24879):        at android.app.Activity.performCreate(Activity.java:7073)
E/AndroidRuntime(24879):        at android.app.Activity.performCreate(Activity.java:7064)
E/AndroidRuntime(24879):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
E/AndroidRuntime(24879):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2850)
E/AndroidRuntime(24879):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2975)
E/AndroidRuntime(24879):        at android.app.ActivityThread.-wrap11(Unknown Source:0)
E/AndroidRuntime(24879):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1705)
E/AndroidRuntime(24879):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(24879):        at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(24879):        at android.app.ActivityThread.main(ActivityThread.java:6615)
E/AndroidRuntime(24879):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24879):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime(24879):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
E/AndroidRuntime(24879): Caused by: android.view.InflateException: Binary XML file line #13: Failed to resolve attribute at index 4: TypedValue{t=0x2/d=0x7f040003 a=-1}
E/AndroidRuntime(24879): Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 4: TypedValue{t=0x2/d=0x7f040003 a=-1}
E/AndroidRuntime(24879):        at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:726)
E/AndroidRuntime(24879):        at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7874)
E/AndroidRuntime(24879):        at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:439)
E/AndroidRuntime(24879):        at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:370)
E/AndroidRuntime(24879):        at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:368)
E/AndroidRuntime(24879):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
E/AndroidRuntime(24879):        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
E/AndroidRuntime(24879):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
E/AndroidRuntime(24879):        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
E/AndroidRuntime(24879):        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
E/AndroidRuntime(24879):        at zendesk.messaging.ui.MessagingView.<init>(MessagingView.java:48)
E/AndroidRuntime(24879):        at zendesk.messaging.ui.MessagingView.<init>(MessagingView.java:40)
```

**Comment by mjmon** [comment] 2020-06-12 14:16
@emostar can you please have a look on the PR for this :)

**Comment by alan2030** [comment] 2020-07-14 08:41
@emostar Could you please tell us if you are planning to finish the update? If no, I will go native on both platforms. Thank you

**Comment by mjmon** [comment] 2020-07-15 04:19
An Alternative is to use Ened's Pull request. It only works for iOS since
it has issue for android.
You can use Emostar's for Android. Zendesk only supports V1 SDK until
December though

**Comment by emostar** [comment] 2020-07-15 06:38
@alan2030 Yes, I'd love to get #20 merged in, but it needs to work for Android as well before it can be published.

**Comment by VytorCalixto** [comment] 2020-08-18 13:22
So, zendesk just announced that the V1 will stop being supported in December 16, 2020. What can we do to help in the migration?

**Comment by alan2030** [comment] 2020-10-16 11:23
@emostar I think #20 is good to go now, can you check please?

**Comment by mjmon** [comment] 2020-10-19 10:38
@emostar Yes #20 is working after following the Android example.

**Comment by emostar** [comment] 2020-10-23 06:37
Thanks for the work, @ened! This change has been pushed to pub.dev as v2.0.0.

**Closed by emostar** 2020-10-23 06:37 UTC

**Comment by MuthuSubramaniam** [comment] 2020-10-27 05:53
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mobi.wallet/zendesk.messaging.MessagingActivity}: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class zendesk.messaging.ui.MessagingView
E/AndroidRuntime(22836): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2747)
E/AndroidRuntime(22836): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)
E/AndroidRuntime(22836): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
E/AndroidRuntime(22836): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
E/AndroidRuntime(22836): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(22836): 	at android.os.Looper.loop(Looper.java:165)
E/AndroidRuntime(22836): 	at android.app.ActivityThread.main(ActivityThread.java:6375)
E/AndroidRuntime(22836): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22836): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
E/AndroidRuntime(22836): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
E/AndroidRuntime(22836): Caused by: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class zendesk.messaging.ui.MessagingView
E/AndroidRuntime(22836): Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class zendesk.messaging.ui.MessagingView
E/AndroidRuntime(22836): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(22836): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
E/AndroidRuntime(22836): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
E/AndroidRuntime(22836): 	at android.view.LayoutInflater.createView(LayoutInflater.java:652)
E/AndroidRuntime(22836): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:812)
E/AndroidRuntime(22836): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
E/AndroidRuntime(22836): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
E/AndroidRuntime(22836): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
E/AndroidRuntime(22836): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
E/AndroidRuntime(22836): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
E/AndroidRuntime(22836): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
E/AndroidRuntime(22836): 	at zendesk.messaging.MessagingActivity.onCreate(MessagingActivity.java:121)
E/AndroidRuntime(22836): 	at android.app.Activity.performCreate(Activity.java:6845)
E/AndroidRuntime(22836): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
E/AndroidRuntime(22836): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2700)
E/AndroidRuntime(22836): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)
E/AndroidRuntime(22836): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
E/AndroidRuntime(22836): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
E/AndroidRuntime(22836): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(22836): 	at android.os.Looper.loop(Looper.java:165)
E/AndroidRuntime(22836): 	at android.app.ActivityThread.main(ActivityThread.java:6375)
E/AndroidRuntime(22836): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22836): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
E/AndroidRuntime(22836): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
E/AndroidRuntime(22836): Caused by: android.view.InflateException: Binary XML file line #13: Failed to resolve attribute at index 4: TypedValue{t=0x2/d=0x7f040003 a=-1}
E/AndroidRuntime(22836): Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 4: TypedValue{t=0x2/d=0x7f040003 a=-1}
E/AndroidRuntime(22836): 	at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:718)
E/AndroidRuntime(22836): 	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7270)
E/AndroidRuntime(22836): 	at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:438)
E/AndroidRuntime(22836): 	at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:370)
E/AndroidRuntime(22836): 	at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:369)
E/AndroidRuntime(22836): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:885)
E/AndroidRuntime(22836): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
E/AndroidRuntime(22836): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:886)
E/AndroidRuntime(22836): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:496)
E/AndroidRuntime(22836): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
E/AndroidRuntime(22836): 	at zendesk.messaging.ui.MessagingView.<init>(MessagingView.java:49)
E/AndroidRuntime(22836): 	at zendesk.messaging.ui.MessagingView.<init>(MessagingView.java:41)
E/AndroidRuntime(22836): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
E/AndroidRuntime(22836): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
E/AndroidRuntime(22836): 	at android.view.LayoutInflater.createView(LayoutInflater.java:652)
E/AndroidRuntime(22836): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:812)
E/AndroidRuntime(22836): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
E/AndroidRuntime(22836): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
E/AndroidRuntime(22836): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
E/AndroidRuntime(22836): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
E/AndroidRuntime(22836): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
E/AndroidRuntime(22836): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
E/AndroidRuntime(22836): 	at zendesk.messaging.MessagingActivity.onCreate(MessagingActivity.java:121)
E/AndroidRuntime(22836): 	at android.app.Activity.performCreate(Activity.java:6845)
E/AndroidRuntime(22836): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
E/AndroidRuntime(22836): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2700)
E/AndroidRuntime(22836): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)
E/AndroidRuntime(22836): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
E/AndroidRuntime(22836): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
E/AndroidRuntime(22836): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(22836): 	at android.os.Looper.loop(Looper.java:165)
E/AndroidRuntime(22836): 	at android.app.ActivityThread.main(ActivityThread.java:6375)
E/AndroidRuntime(22836): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22836): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
E/AndroidRuntime(22836): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)



![image](https://user-images.githubusercontent.com/39517706/97262385-ad172d80-185b-11eb-9b53-f1474a98e25d.png)


Still the issue is there @emostar 
Working perfectly in iOS but unfortunately android getting crash with the above message!!

do you think anything wrong in my config?

**Comment by mjmon** [comment] 2020-10-27 06:47
You don't need to import pigeon. You need to add an appropriate theme in the application section in AndroidManifest. 
```
    <application
        ...
        android:icon="@mipmap/ic_launcher"
        android:theme="@style/LaunchTheme"
        >
```

Also add the corresponding theme which is `LaunchTheme` on my case inside your `styles.xml`.

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="NormalTheme" parent="@android:style/Theme.Black.NoTitleBar">
        <item name="android:windowBackground">@android:color/white</item>
    </style>
    <style name="LaunchTheme" parent="ZendeskSdkTheme.Light">
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
</resources>
```

**Comment by MuthuSubramaniam** [comment] 2020-10-27 07:33
![image](https://user-images.githubusercontent.com/39517706/97270108-8fe95b80-1869-11eb-84e3-07bde5115890.png)

![image](https://user-images.githubusercontent.com/39517706/97270163-aabbd000-1869-11eb-94d2-1c8a40b51040.png)
@ened @mjmon my bad still i am getting crash with the same error.

**Comment by ened** [comment] 2020-10-27 09:09
@MuthuSubramaniam looks like the change needs to be in `<application`, not `<activity`.

**Comment by MuthuSubramaniam** [comment] 2020-10-27 09:27
> @MuthuSubramaniam looks like the change needs to be in `<application`, not `<activity`.

Excellent guess!. my bad. Thanks for the info! I will write a medium on this. would be helpful for some ppl like me!

**Comment by ened** [comment] 2020-10-27 10:24
A PR to this projects README file would be a great start, too. 👍

**Comment by empenergy** [comment] 2020-10-29 04:46
@ened Thank you so much for doing this.  I was hoping the new v2 SDK Android would fix my issue but it did not.  

I have not been able to get the plugin to work since the V2 embedding changes in Android even before this change.  If I revert back to before that, the chat will pop up in my application.  I can get it to work fine in the example however with the V2 embedding.  It just will not work in my app.  Are there other changes that need to be in the Android.manifest, pubspec.yaml, or build.gradle that I am missing in my app?

**Comment by ened** [comment] 2020-10-29 06:51
@empenergy yes you'll need to adjust the AndroidManifest.xml's <application tag to use a specific theme. Please refer to the project example for details.

**Comment by MuthuSubramaniam** [comment] 2020-10-31 01:36
yes after adding that its absolutely working fine!

Thanks again @ened
